channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - matplotlib=3.1.0
  - nbgrader=0.5.5
  - notebook=5.7.8
  - numpy=1.16.3
  - pandas=0.23.4
  - python=3.7.3
  - scikit-learn=0.21.2
  - category_encoders=2.0.0
  - pip:
    - ldsagrader==0.1.11
