channels:
  - conda-forge
  - msys2
  - defaults
dependencies:
  - python=3.7
  - jupyter=1.0.0
  - pandas=0.24.1
  - nbgrader=0.5.5
  - requests=2.22.0
  - psycopg2=2.7.6.1
  - sqlalchemy=1.3.5
  - beautifulsoup4=4.7.1
  - pillow=6.1.0
