channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - jupyter=1.0.0
  - pandas=0.25.1
  - nbgrader=0.6.0
  - scikit-learn=0.21.3
  - matplotlib=3.1.1
  - seaborn=0.9.0
  - numpy=1.17.1
  - nltk=3.4.5
  - spacy=2.1.8
  - scipy=1.3.1
  - pip=19.2.3
  - pip:
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.1.0/en_core_web_md-2.1.0.tar.gz#egg=en_core_web_md
