channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.3
  - jupyter==1.0.0
  - matplotlib==3.1.1
  - mlxtend==0.17.0
  - nbgrader==0.6.0
  - numpy==1.16.3
  - pandas==0.25.2
  - scikit-learn==0.21.3
  - scipy==1.3.1
  - seaborn==0.9.0
